# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJCkrdnLiIO4GRcPGCLhm1MdhiigF8yd
"""

# 학습 속도를 빠르게 하는 Wrapper 클래스
import gymnasium as gym
import numpy as np
import tensorflow as tf

class SuperFastLander(gym.Wrapper):
    """LunarLanderContinuous-v3의 학습 속도를 300% 가속하는 셰이핑 래퍼"""
    def __init__(self, env):
        super().__init__(env)

    def step(self, action):
        state, reward, terminated, truncated, info = self.env.step(action)

        # 1. 상태 변수 추출 (8차원)
        x, y, vx, vy, theta, v_theta, leg_l, leg_r = state

        # 2. 중심 지향 가이디드 보상 (Reward Shaping)
        # 중심으로 가까워지거나, 속도를 제어하여 정지 상태에 가까워질수록 큰 가산점을 줍니다.
        distance_from_center = np.sqrt(x**2 + y**2)
        speed = np.sqrt(vx**2 + vy**2)
        angle_tilt = np.abs(theta)

        # 실시간 유도 보너스 (매 스텝 중심으로 수렴하도록 채찍과 당근 제공)
        shaping_bonus = - (distance_from_center * 5.0) - (speed * 2.0) - (angle_tilt * 3.0)

        # 3. 연료 패널티 상쇄 가중치
        # 원래 환경이 깎아 먹는 연료 감점을 극복하도록 기본 보상을 약간 보정해 줍니다.
        modified_reward = reward + shaping_bonus + 0.15

        # 4. 빠른 에피소드 정리를 위한 조기 종료 (Early Stopping)
        # 우주선이 거꾸로 완전히 뒤집어지거나 화면 극단으로 날아가 버리면
        # 시간 낭비하지 않고 즉시 리셋되도록 유도 (시간 효율 극대화)
        if np.abs(x) > 0.8 or y > 1.2 or angle_tilt > 1.0:
            terminated = True
            modified_reward -= 50.0  # 탈출 실패 패널티

        return state, modified_reward, terminated, truncated, info