# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJCkrdnLiIO4GRcPGCLhm1MdhiigF8yd
"""

# 학습 속도를 빠르게 하는 Wrapper 클래스
import gymnasium as gym
import numpy as np
import tensorflow as tf

class SuperFastLander(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)

    def step(self, action):
        state, reward, terminated, truncated, info = self.env.step(action)
        x, y, vx, vy, theta, v_theta, leg_l, leg_r = state
        
        angle_tilt = np.abs(theta)


        # 추락이 홗리한 경우 조기 종료
        # - 좌우 경계 탈출 (abs(x) > 0.95)
        # - 완전히 땅 밑으로 뚫고 내려감 (y < 0.0) -> 사실상 추락
        # - 우주선이 완전히 뒤집어짐 (abs(theta) > 1.5, 즉 90도 이상 꺾임)
        if np.abs(x) > 0.95 or y < 0.0 or angle_tilt > 1.5:
            terminated = True
            modified_reward -= 100.0  # 확실한 추락 패널티 부여

        return state, modified_reward, terminated, truncated, info