# -*- coding: utf-8 -*-
"""transformer_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4zWbqo73einyJfXapniXBC8uJxOU-Wz
"""

import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

# 텍스트 토큰에 대한 트랜스포머 임베딩
class TextEmbedding(layers.Layer):
    def __init__(self, input_dim, output_dim, maxlen=5000, mask_zero=False, **kwargs):
        super().__init__(**kwargs)

        self.token_emb = layers.Embedding(
            input_dim=input_dim,
            output_dim=output_dim,
            mask_zero=mask_zero
        )

        self.pos_emb = layers.Embedding(
            input_dim=maxlen,
            output_dim=output_dim
        )

        # [추가] 임베딩된 벡터들을 정규화하여 안정성을 높입니다.
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)
        self.dropout = layers.Dropout(0.1) # 보통 임베딩 직후에도 드롭아웃을 섞어줍니다.

    def call(self, x):
        seq_len = tf.shape(x)[1]

        # 1. 위치 및 토큰 임베딩 추출
        positions = tf.range(start=0, limit=seq_len, delta=1)
        position_embeddings = self.pos_emb(positions)
        token_embeddings = self.token_emb(x)

        # 2. 두 임베딩을 더함
        x = token_embeddings + position_embeddings

        # 3. [핵심] 정규화와 드롭아웃 적용
        x = self.layernorm(x)
        return self.dropout(x)

    def compute_mask(self, inputs, mask=None):
        return self.token_emb.compute_mask(inputs)

# 이미지 토큰(패치)에 대한 트랜스포머 임베딩
class PatchEmbedding(layers.Layer):
    def __init__(self, patch_size, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.patch_size = patch_size
        self.embed_dim = embed_dim

    def build(self, input_shape):
        # 1. 입력 이미지 크기를 패치 크기의 배수로 맞추기 위한 목표 크기 계산
        # 예: 이미지 67, 패치 8 -> (67 // 8 + 1) * 8 = 72로 리사이즈
        self.target_h = int(np.ceil(input_shape[1] / self.patch_size) * self.patch_size)
        self.target_w = int(np.ceil(input_shape[2] / self.patch_size) * self.patch_size)
        
        # 2. 내부 리사이징 레이어 선언
        self.resize_layer = layers.Resizing(self.target_h, self.target_w)
        
        # 3. 바뀐 크기를 바탕으로 패치 개수 재계산
        self.num_patches = (self.target_h // self.patch_size) * (self.target_w // self.patch_size)
        
        # 4. 나머지 레이어 설정
        self.projection = layers.Conv2D(
            filters=self.embed_dim,
            kernel_size=self.patch_size,
            strides=self.patch_size,
            padding="valid"
        )
        self.pos_emb = layers.Embedding(input_dim=self.num_patches, output_dim=self.embed_dim)
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)

    def call(self, images):
        # 자동으로 리사이징 수행
        images = self.resize_layer(images)
        
        batch_size = tf.shape(images)[0]
        patches = self.projection(images)
        patches = tf.reshape(patches, (batch_size, -1, self.embed_dim))

        positions = tf.range(start=0, limit=self.num_patches, delta=1)
        encoded = patches + self.pos_emb(positions)

        return self.layernorm(encoded)

# 숫자 시계열에 대한 트랜스포머 임베딩(패치 가능)
class TimeSeriesEmbedding(layers.Layer):
    def __init__(self, seq_length, patch_size, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.patch_size = patch_size
        self.embed_dim = embed_dim
        self.num_patches = seq_length // patch_size

        # 각 패치를 임베딩 공간으로 투영
        self.projection = layers.Dense(embed_dim)

        # 위치 임베딩
        self.pos_emb = layers.Embedding(input_dim=self.num_patches, output_dim=embed_dim)
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)

    def call(self, x):
        # x: (batch, seq_length, num_vars) -> (None, 90, 3)

        # 1. 텐서의 정적 shape 정보를 최대한 활용합니다.
        # batch_size를 고정하지 않고 나머지 차원만 수동으로 계산해줍니다.
        # (batch, 9, 10 * 3) 형태로 리셰이프
        num_vars = x.shape[-1]
        x = tf.reshape(x, (-1, self.num_patches, self.patch_size * num_vars))

        # 2. 이제 마지막 차원이 (patch_size * num_vars)로 고정되었으므로 Dense가 작동합니다.
        x = self.projection(x)

        # 3. 위치 정보 추가
        positions = tf.range(start=0, limit=self.num_patches, delta=1)
        x = x + self.pos_emb(positions)

        return self.layernorm(x)

    # Keras가 모델의 흐름을 미리 파악할 수 있도록 출력 형태를 정의해줍니다.
    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.num_patches, self.embed_dim)

# 모든 데이터에 공통인 TransformerBlock ( 셀프인텐션 + FFN)
class TransformerBlock(layers.Layer):
    def __init__(self,
                 num_heads=8,
                 ff_dim=None,
                 dropout=0.1,
                 return_sequences=True,  # 다시 추가
                 use_causal_mask=False,  # 다시 추가
                 **kwargs):
        super().__init__(**kwargs)
        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.dropout_rate = dropout
        self.return_sequences = return_sequences
        self.use_causal_mask = use_causal_mask

    def build(self, input_shape):
        embed_dim = input_shape[-1]
        if self.ff_dim is None:
            self.ff_dim = 4 * embed_dim

        self.att = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=embed_dim // self.num_heads
        )

        self.ffn = tf.keras.Sequential([
            layers.Dense(self.ff_dim, activation=tf.nn.gelu),
            layers.Dropout(self.dropout_rate),
            layers.Dense(embed_dim),
            layers.Dropout(self.dropout_rate)
        ])

        self.norm1 = layers.LayerNormalization(epsilon=1e-6)
        self.norm2 = layers.LayerNormalization(epsilon=1e-6)
        self.drop = layers.Dropout(self.dropout_rate)

    def call(self, x, training=None, mask=None):
        # 1. Mask 설정 (텍스트용 mask 지원)
        attention_mask = None
        if mask is not None:
            attention_mask = mask[:, tf.newaxis, :]

        # --- PART 1: Self-Attention (Pre-LN) ---
        x_norm = self.norm1(x)
        attn_output = self.att(
            x_norm, x_norm,
            attention_mask=attention_mask,
            use_causal_mask=self.use_causal_mask,
            training=training
        )
        x = x + self.drop(attn_output, training=training)

        # --- PART 2: FFN (Pre-LN) ---
        x_norm = self.norm2(x)
        ffn_output = self.ffn(x_norm, training=training)
        x = x + ffn_output

        # 2. Return sequences 처리 (이미지/텍스트 공통)
        if self.return_sequences:
            return x
        else:
            # 마지막 토큰(패치)의 정보만 추출 (주로 텍스트 분류 시 사용)
            return x[:, -1, :]

    def compute_mask(self, inputs, mask=None):
        # 마스킹 정보를 다음 층으로 전달
        return mask