# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJCkrdnLiIO4GRcPGCLhm1MdhiigF8yd
"""

# ppo_helper.py
import numpy as np
import tensorflow as tf

def get_log_prob(mu, std, action):
    """연속 행동에 대한 가우시안 로그 확률 계산"""
    var = tf.square(std)
    # 수식 안정성을 위해 std가 0이 되는 것을 방지하는 미소값(1e-6) 추가
    log_scale = tf.math.log(std + 1e-6) + 0.5 * tf.math.log(2.0 * np.pi)
    log_prob = -tf.square(action - mu) / (2.0 * var + 1e-6) - log_scale
    return tf.reduce_sum(log_prob, axis=-1)

def compute_gae_and_targets(rewards, values, next_values, dones, gamma=0.99, lmbda=0.95):
    """GAE(Advantage) 및 Critic의 target_value 일괄 계산"""
    advantages = np.zeros_like(rewards)
    gae = 0.0
    for t in reversed(range(len(rewards))):
        mask = 1.0 - dones[t]
        td_target = rewards[t] + gamma * next_values[t] * mask
        delta = td_target - values[t]
        gae = delta + gamma * lmbda * mask * gae
        advantages[t] = gae
    return advantages, advantages + values

class PPOUpdater:
    """메인 코드의 모델들을 전달받아 정적 그래프 기반 파라미터 업데이트를 수행하는 클래스"""
    def __init__(self, actor_mu, actor_log_std, critic, actor_lr=3e-4, critic_lr=1e-3, epsilon=0.2):
        self.actor_mu = actor_mu
        self.actor_log_std = actor_log_std
        self.critic = critic

        self.actor_optimizer = tf.keras.optimizers.Adam(learning_rate=actor_lr)
        self.critic_optimizer = tf.keras.optimizers.Adam(learning_rate=critic_lr)
        self.epsilon = epsilon

    @tf.function # <--- 텐서플로 정적 그래프 컴파일 가동
    def train_step(self, states_t, actions_t, old_log_probs_t, advantages_t, target_values_t):
        """Persistent GradientTape를 활용한 액터-크리틱 통합 고속 업데이트 단계"""
        with tf.GradientTape(persistent=True) as tape:
            # 1. Actor Update 로직
            new_mu = self.actor_mu(states_t, training=True)

            # 🔥 [수정 가이드] actor_log_std가 케라스 Layer(호출가능)인지, tf.Variable(변수)인지 판별하여 처리
            if callable(self.actor_log_std):
                new_std = tf.exp(self.actor_log_std(states_t, training=True))
            else:
                new_std = tf.exp(self.actor_log_std)

            new_log_probs = get_log_prob(new_mu, new_std, actions_t)

            ratio = tf.exp(new_log_probs - old_log_probs_t)
            surr1 = ratio * advantages_t
            surr2 = tf.clip_by_value(ratio, 1.0 - self.epsilon, 1.0 + self.epsilon) * advantages_t
            actor_loss = -tf.reduce_mean(tf.minimum(surr1, surr2))

            # 2. Critic Update 로직
            predicted_values = tf.squeeze(self.critic(states_t, training=True), axis=-1)
            critic_loss = tf.reduce_mean(tf.square(target_values_t - predicted_values))

        # 가중치 갱신 대상 선별
        if callable(self.actor_log_std):
            actor_vars = self.actor_mu.trainable_variables + self.actor_log_std.trainable_variables
        else:
            actor_vars = self.actor_mu.trainable_variables + [self.actor_log_std]

        actor_grads = tape.gradient(actor_loss, actor_vars)
        self.actor_optimizer.apply_gradients(zip(actor_grads, actor_vars))

        critic_grads = tape.gradient(critic_loss, self.critic.trainable_variables)
        self.critic_optimizer.apply_gradients(zip(critic_grads, self.critic.trainable_variables))

        del tape
        return actor_loss, critic_loss

    def update(self, states, actions, old_log_probs, advantages, target_values, epochs=4, batch_size=64):
        """기존 넘파이 데이터를 텐서로 포맷팅하고, 미니배치로 분할하여 고속 반복 업데이트 수행"""
        # 정규화(Advantage) 처리를 통해 PPO 확률 그라디언트 안정화 추가
        advantages = (advantages - np.mean(advantages)) / (np.std(advantages) + 1e-8)

        data_size = len(states)

        for _ in range(epochs):
            # 🔥 [속도 최적화] 매 에포크마다 무작위로 인덱스를 섞어 MCMC처럼 골고루 탐색하도록 유도
            indices = np.arange(data_size)
            np.random.shuffle(indices)

            # 미니배치 루프 가동
            for start in range(0, data_size, batch_size):
                end = start + batch_size
                batch_idx = indices[start:end]

                # 미니배치 슬라이싱 및 텐서 변환
                states_t = tf.convert_to_tensor(states[batch_idx], dtype=tf.float32)
                actions_t = tf.convert_to_tensor(actions[batch_idx], dtype=tf.float32)
                old_log_probs_t = tf.convert_to_tensor(old_log_probs[batch_idx], dtype=tf.float32)
                advantages_t = tf.convert_to_tensor(advantages[batch_idx], dtype=tf.float32)
                target_values_t = tf.convert_to_tensor(target_values[batch_idx], dtype=tf.float32)

                # 정적 그래프 최적화 함수 호출
                self.train_step(states_t, actions_t, old_log_probs_t, advantages_t, target_values_t)