# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMSs6ly-3smNqfUNTYz2Thqbb_XaEYLf
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# [레이어 1] Position Embedding
class PositionEmbedding(layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super().__init__()
        # mask_zero=True가 모든 마스킹의 시작점입니다!
        self.token_emb = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim, mask_zero=True)
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        # 단어 벡터와 위치 벡터를 더합니다.
        # 이때 Embedding(mask_zero=True)에서 만들어진 마스크 정보가 결과값에 '몰래' 붙어서 다음 층으로 전달됩니다.
        return self.token_emb(x) + positions

# [레이어 2] Transformer Block (감성 분석용)
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, use_causal_mask=False, rate=0.1):
        super().__init__()
        # 1. 생성 시(True), 분석 시(False)를 객체 생성 때 결정합니다.
        self.use_causal_mask = use_causal_mask
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim//num_heads)
        self.ffn = keras.Sequential([
            layers.Dense(ff_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs, training=True, mask=None):
        # 2. 패딩 마스크 처리 (0번 토큰 무시)
        padding_mask = None
        if mask is not None:
            padding_mask = tf.cast(mask[:, tf.newaxis, tf.newaxis, :], dtype="int32")

        # 3. 객체 생성 시 설정한 use_causal_mask 값에 따라 동작이 달라집니다.
        attn_output = self.att(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=padding_mask,
            use_causal_mask=self.use_causal_mask # 여기서 스위칭!
        )

        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        return self.layernorm2(out1 + ffn_output)