# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnfpejKW8gL3exEo9yQXDgMX4wOgSc9m
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class PositionEncoding(layers.Layer):
    """
    Embedding 층 바로 뒤에 위치하여 단어의 위치 정보(Position)를 더해주는 레이어입니다.
    케라스 Embedding 층의 mask_zero=True 설정을 그대로 보존합니다.
    """
    def __init__(self, max_steps=2048, **kwargs):
        super().__init__(**kwargs)
        self.supports_masking = True
        self.max_steps = max_steps
        self.pos_emb = None

    def build(self, input_shape):
        # 앞 레이어(Embedding)의 출력 차원을 자동으로 가져옵니다.
        embed_dim = input_shape[-1]
        self.pos_emb = layers.Embedding(input_dim=self.max_steps, output_dim=embed_dim)
        super().build(input_shape)

    def call(self, x):
        seq_len = tf.shape(x)[1]
        positions = tf.range(start=0, limit=seq_len, delta=1)
        positions = self.pos_emb(positions)
        return x + positions

    def compute_mask(self, inputs, mask=None):
        return mask

    def get_config(self):
        config = super().get_config()
        config.update({"max_steps": self.max_steps})
        return config


class TransformerBlock(layers.Layer):
    """
    Multi-Head Attention과 Feed Forward Network를 결합한 트랜스포머의 기본 블록입니다.
    use_causal_mask 설정을 통해 문장 생성(True)과 감성 분석(False) 모두 지원합니다.
    """
    def __init__(self, num_heads, ff_dim, use_causal_mask=False, rate=0.1, **kwargs):
        super().__init__(**kwargs)
        self.supports_masking = True
        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.use_causal_mask = use_causal_mask
        self.rate = rate

        # 레이어 선언 (build에서 구체화됨)
        self.att = None
        self.ffn = None
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(rate)
        self.dropout2 = layers.Dropout(rate)

    def build(self, input_shape):
        embed_dim = input_shape[-1]
        # MultiHeadAttention의 key_dim을 자동으로 계산하여 생성합니다.
        self.att = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=embed_dim // self.num_heads
        )
        self.ffn = keras.Sequential([
            layers.Dense(self.ff_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        super().build(input_shape)

    def call(self, inputs, training=True, mask=None):
        # 케라스 3.x 환경에서의 안정적인 마스킹을 위해 차원 확장
        attention_mask = None
        if mask is not None:
            attention_mask = mask[:, tf.newaxis, :]

        attn_output = self.att(
            query=inputs,
            key=inputs,
            value=inputs,
            attention_mask=attention_mask,
            use_causal_mask=self.use_causal_mask,
            training=training
        )
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_heads": self.num_heads,
            "ff_dim": self.ff_dim,
            "use_causal_mask": self.use_causal_mask,
            "rate": self.rate,
        })
        return config