# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNr1rsf0ge2ncXcz-8mD3D66kwJyyyBf
"""

import tensorflow as tf
from tensorflow.keras import layers

# 수정된 TokenEmbedding (LayerNorm 추가)
class TokenEmbedding(layers.Layer):
    def __init__(self, input_dim, output_dim, maxlen=5000, mask_zero=False, **kwargs):
        super().__init__(**kwargs)

        self.token_emb = layers.Embedding(
            input_dim=input_dim,
            output_dim=output_dim,
            mask_zero=mask_zero
        )

        self.pos_emb = layers.Embedding(
            input_dim=maxlen,
            output_dim=output_dim
        )

        # [추가] 임베딩된 벡터들을 정규화하여 안정성을 높입니다.
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)
        self.dropout = layers.Dropout(0.1) # 보통 임베딩 직후에도 드롭아웃을 섞어줍니다.

    def call(self, x):
        seq_len = tf.shape(x)[1]

        # 1. 위치 및 토큰 임베딩 추출
        positions = tf.range(start=0, limit=seq_len, delta=1)
        position_embeddings = self.pos_emb(positions)
        token_embeddings = self.token_emb(x)

        # 2. 두 임베딩을 더함
        x = token_embeddings + position_embeddings

        # 3. [핵심] 정규화와 드롭아웃 적용
        x = self.layernorm(x)
        return self.dropout(x)

    def compute_mask(self, inputs, mask=None):
        return self.token_emb.compute_mask(inputs)

# 수정된 PatchEmbedding (LayerNorm 추가)
class PatchEmbedding(layers.Layer):
    def __init__(self, patch_size, embed_dim, num_patches, **kwargs):
        super().__init__(**kwargs)
        self.patch_size = patch_size
        self.embed_dim = embed_dim
        self.num_patches = num_patches

        self.projection = layers.Conv2D(
            filters=embed_dim,
            kernel_size=patch_size,
            strides=patch_size,
            padding="valid"
        )
        self.pos_emb = layers.Embedding(input_dim=num_patches, output_dim=embed_dim)

        # 패치 투영 후 초기 정규화를 수행하여 학습 안정성을 높입니다.
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)

    def call(self, images):
        batch_size = tf.shape(images)[0]

        # 1. 이미지를 패치로 나누고 선형 투영
        patches = self.projection(images)
        patches = tf.reshape(patches, (batch_size, -1, self.embed_dim))

        # 2. 위치 임베딩 생성 및 더하기
        positions = tf.range(start=0, limit=self.num_patches, delta=1)
        encoded = patches + self.pos_emb(positions)

        # 3. 마지막 정규화 거친 후 반환
        return self.layernorm(encoded)

# 수정된 TransformerBlock (Pre-LN + GELU 적용)
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads=8, ff_dim=None, dropout=0.1, **kwargs):
        super().__init__(**kwargs)
        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.dropout_rate = dropout

    def build(self, input_shape):
        embed_dim = input_shape[-1]
        if self.ff_dim is None:
            self.ff_dim = 4 * embed_dim

        # Attention 레이어
        self.att = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=embed_dim // self.num_heads
        )

        # Feed Forward Network (ReLU -> GELU로 변경)
        self.ffn = tf.keras.Sequential([
            layers.Dense(self.ff_dim, activation=tf.nn.gelu),
            layers.Dropout(self.dropout_rate),
            layers.Dense(embed_dim),
            layers.Dropout(self.dropout_rate)
        ])

        # Pre-LN을 위한 레이어들
        self.norm1 = layers.LayerNormalization(epsilon=1e-6)
        self.norm2 = layers.LayerNormalization(epsilon=1e-6)
        self.drop = layers.Dropout(self.dropout_rate)

    def call(self, x, training=None):
        # --- PART 1: Self-Attention (Pre-LN) ---
        # 1. 들어가기 전에 먼저 정규화 (Pre-LN)
        x_norm = self.norm1(x)

        # 2. 어텐션 수행
        attn_output = self.att(x_norm, x_norm, training=training)

        # 3. 잔차 연결 (Original x와 합치기)
        x = x + self.drop(attn_output, training=training)

        # --- PART 2: Feed Forward Network (Pre-LN) ---
        # 4. 다시 들어가기 전에 정규화
        x_norm = self.norm2(x)

        # 5. FFN 수행
        ffn_output = self.ffn(x_norm, training=training)

        # 6. 잔차 연결 및 최종 반환
        return x + ffn_output