# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiIxHdjyr9qtsr0LQX5Gwy7nLLlkTjeF
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# [레이어 1] 단어 의미와 위치 정보를 합치는 클래스
class PositionEmbedding(layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super(PositionEmbedding, self).__init__()
        self.token_emb = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        # 입력 데이터 x의 길이를 동적으로 가져와 위치 정보를 만듭니다.
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

# [레이어 2] 실제 학습이 일어나는 트랜스포머 블록 클래스
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, num_layers=1, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_layers = num_layers

        # 실제 연산 레이어 (안정적인 1층 구조)
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = keras.Sequential([
            layers.Dense(ff_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(rate)
        self.dropout2 = layers.Dropout(rate)

    def call(self, inputs, training=None):
        # 1. Attention + Residual
        attn_output = self.att(inputs, inputs, use_causal_mask=True)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)

        # 2. Feed Forward + Residual
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        x = self.layernorm2(out1 + ffn_output)

        # 3. 마지막 시점 벡터 추출
        return x[:, -1, :]