# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwfEALy769KFqMsDd6_qs44PBlgHeXuK
"""

import tensorflow as tf
from tensorflow.keras import layers

# ---------------------------------------------------------
#  텍스트 데이터용 Embedding + Positional Encoding
# ---------------------------------------------------------
class TextEmbedding(layers.Layer):
    def __init__(self, input_dim, output_dim, maxlen=5000, mask_zero=False):
        super().__init__()

        self.token_emb = layers.Embedding(
            input_dim=input_dim,
            output_dim=output_dim,
            mask_zero=mask_zero
        )

        self.pos_emb = layers.Embedding(
            input_dim=maxlen,
            output_dim=output_dim
        )

    def call(self, x):

        seq_len = tf.shape(x)[1]

        positions = tf.range(start=0, limit=seq_len, delta=1)

        position_embeddings = self.pos_emb(positions)

        token_embeddings = self.token_emb(x)

        return token_embeddings + position_embeddings

    def compute_mask(self, inputs, mask=None):
        return self.token_emb.compute_mask(inputs)


# ---------------------------------------------------------
#  이미지 데이터용 Embedding + Positional Encoding
# ---------------------------------------------------------
class ImageEmbedding(layers.Layer):
    def __init__(self, patch_size, embed_dim, num_patches):
        super().__init__()
        self.projection = layers.Conv2D(
            filters=embed_dim, kernel_size=patch_size, strides=patch_size
        )
        self.pos_emb = layers.Embedding(input_dim=num_patches, output_dim=embed_dim)

    def call(self, images):
        patches = self.projection(images)
        batch_size = tf.shape(images)[0]
        patches = tf.reshape(patches, (batch_size, -1, embed_dim))

        positions = tf.range(start=0, limit=num_patches, delta=1)
        return patches + self.pos_emb(positions)

# ---------------------------------------------------------
#  텍스트/ 이미지 공통 Multi_Head Attention + FFN
# ---------------------------------------------------------
class TransformerBlock(layers.Layer):
    """
    Transformer block

    Structure
    ---------
    Self Attention
    → Residual
    → LayerNorm
    → Feed Forward Network
    → Residual
    → LayerNorm
    """

    def __init__(self,
                 num_heads=8,
                 ff_dim=None,
                 dropout=0.1,
                 return_sequences=True,
                 use_causal_mask=False):

        super().__init__()

        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.dropout_rate = dropout
        self.return_sequences = return_sequences
        self.use_causal_mask = use_causal_mask

    def build(self, input_shape):

        embed_dim = input_shape[-1]

        if self.ff_dim is None:
            self.ff_dim = 4 * embed_dim

        self.att = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=embed_dim // self.num_heads
        )

        self.ffn = tf.keras.Sequential([
            layers.Dense(self.ff_dim, activation="relu"),
            layers.Dense(embed_dim)
        ])

        self.norm1 = layers.LayerNormalization()
        self.norm2 = layers.LayerNormalization()

        self.drop1 = layers.Dropout(self.dropout_rate)
        self.drop2 = layers.Dropout(self.dropout_rate)

    def call(self, x, training=None, mask=None):

        attention_mask = None

        if mask is not None:
            attention_mask = mask[:, tf.newaxis, :]

        attn_output = self.att(
            x,
            x,
            attention_mask=attention_mask,
            use_causal_mask=self.use_causal_mask
        )

        attn_output = self.drop1(attn_output, training=training)

        out1 = self.norm1(x + attn_output)

        ffn_output = self.ffn(out1)

        ffn_output = self.drop2(ffn_output, training=training)

        out2 = self.norm2(out1 + ffn_output)

        if self.return_sequences:
            return out2
        else:
            return out2[:, -1, :]

    def compute_mask(self, inputs, mask=None):
        return mask